### ISSUE TITLE
cosmos* address

### ISSUE THREAD

**Issue by kosjak0ff** [ingenuity-build/testnets#2]
How can I create 'cosmos*' wallet address (Rhapsody tesnet) if I used "Manual Configuration"?

**Comment by nodersteam** [comment]
You can use ./build/quicksilverd keys add <YOUR_TEST_WALLET> --keyring-backend=test

**Comment by kosjak0ff** [comment]
this is command for "quick*" address
but question was about "cosmos*" address 
in guide was mention that need 2 addresses with different denoms

**Comment by joe-bowman** [comment]
Sorry; didn't see this until now - we will be suing Keplr for generating cosmos address and interacting with testnet chains. Instructions will be posted once the front end is deployed.
