### ISSUE TITLE
Error create validator

### ISSUE THREAD

**Issue by Geovezaaa** [ingenuity-build/testnets#20]
always Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account quick1fk9qtycszzk32c3hk8xwjwvkhmkc8rv6gg0xzd not found: key not found, but already request fund on qck-tap channel

**Comment by joe-bowman** [comment]
This suggests your node was not synced when you attempted to submit the transaction. As far as your node was concerned, the account doesn't exist because the height at which the transaction was included in a block had not passed (on your local node).
