### ISSUE TITLE
Atom-tap not working/ potential bug in testnet select a validator step

### ISSUE THREAD

**Issue by Andrewzakman** [ingenuity-build/testnets#87]
Hi, the atom-taps won't work even when I pasted "$request cosmos1x079s3v225m29upc5v94fdyjm5ej47nm6yayvn" under the atom-tap. Qck-tap would not work either and no community assistance was provided for me per request under any eligible tabs. Because of that, I am unable to complete the UI task for making a qatom and doing the stake process through the hub. I am unable to proceed past the request assets step per the manual as a result where: "Go on Discord and request the
Asset you need from its
respective "tap" (e.g. atom-tap,
osmo-tap), by typing
"$request" followed by your
Cosmos wallet address."

Because of that I am unable to proceed past the "select a network" step. I am able to select cosmos under choose a network and I have bought plenty of atom tokens so I do not need anything from the atom-faucet anyway, however, nothing else populates upon clicking on cosmos as my network nor is there any steps or buttons to proceed further nor does anything populate like the illustration in the manual. However, I am able to click cosmos as my network and I do have 50+ atom tokens to work with. Please let me know if there is a fix or if there can be created a way past this dilemma. I am stuck on the "select a network" step of the manual as a result where: "You
’ll be directed to the
protocol's Staking Interface.
Please approve those
requests. Once they are
approved, you will be able to
"Choose your Network." and cannot proceed to the "verify wallet details" step per the manual where: "The dropdown will consist of a
list of networks. Once a
network is selected, your wallet
details and the address of the
selected network will be
displayed." and am unable to complete the UI task, stake assets, and mint a qatom on the testnet to make me eligible for the Quicksilver protocol airdrop. :( Please find a fix. i really was looking forward to this project and being a part of the airdrop since I invest so much in the cosmos ecosystem e.g., Atom, osmosis, Juno, SCRT network, Evmos and many, many beta networks and DAOS. I will upload this query under bugs to because what I am experiencing might be some sort of bug issue.

**Comment by Andrewzakman** [comment]
I am reporting as a bug with a ton of screenshots so the team can review the visual proof as well.

**Comment by romanpham** [comment]
cool friend.

**Comment by Andrewzakman** [comment]
> 

Any actual feedback?

**Comment by joe-bowman** [comment]
Closing as no longer relevant.
